thebrandSuccess:
  stylesheets:    [reset.css, bootstrap.min.css, bootstrap-responsive.css, style.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js, validator.js, analytics.js, sidebuttons.js, collection_page.js]

indexSuccess:
  stylesheets:    [reset.css, bootstrap.min.css, bootstrap-responsive.css, style.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js, validator.js, analytics.js, sidebuttons.js, collection_page.js]

all:
  stylesheets:    [reset.css, main.css, bootstrap.min.css, bootstrap-responsive.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface,style.css, pressarea.css]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js, validator.js, analytics.js, sidebuttons.js]
  layout: page_layout