<?php

/**
 * BaseIndexContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $newsletter
 * @property string $catalogue
 * @property string $thebrand
 * @property string $thedesigner
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method string       getNewsletter()  Returns the current record's "newsletter" value
 * @method string       getCatalogue()   Returns the current record's "catalogue" value
 * @method string       getThebrand()    Returns the current record's "thebrand" value
 * @method string       getThedesigner() Returns the current record's "thedesigner" value
 * @method IndexContent setId()          Sets the current record's "id" value
 * @method IndexContent setNewsletter()  Sets the current record's "newsletter" value
 * @method IndexContent setCatalogue()   Sets the current record's "catalogue" value
 * @method IndexContent setThebrand()    Sets the current record's "thebrand" value
 * @method IndexContent setThedesigner() Sets the current record's "thedesigner" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndexContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('index_content');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('newsletter', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('catalogue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('thebrand', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('thedesigner', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}