<?php

/**
 * BaseContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property string $phone
 * 
 * @method integer  getId()    Returns the current record's "id" value
 * @method string   getEmail() Returns the current record's "email" value
 * @method string   getPhone() Returns the current record's "phone" value
 * @method Contacts setId()    Sets the current record's "id" value
 * @method Contacts setEmail() Sets the current record's "email" value
 * @method Contacts setPhone() Sets the current record's "phone" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}