<?php

/**
 * BasePressProductConceptImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image
 * @property string $jpg_location
 * @property string $png_location
 * @property integer $press_product_concept_id
 * @property integer $product_id
 * @property PressProductConcept $PressProductConcept
 * @property Product $Product
 * 
 * @method integer                  getId()                       Returns the current record's "id" value
 * @method string                   getImage()                    Returns the current record's "image" value
 * @method string                   getJpgLocation()              Returns the current record's "jpg_location" value
 * @method string                   getPngLocation()              Returns the current record's "png_location" value
 * @method integer                  getPressProductConceptId()    Returns the current record's "press_product_concept_id" value
 * @method integer                  getProductId()                Returns the current record's "product_id" value
 * @method PressProductConcept      getPressProductConcept()      Returns the current record's "PressProductConcept" value
 * @method Product                  getProduct()                  Returns the current record's "Product" value
 * @method PressProductConceptImage setId()                       Sets the current record's "id" value
 * @method PressProductConceptImage setImage()                    Sets the current record's "image" value
 * @method PressProductConceptImage setJpgLocation()              Sets the current record's "jpg_location" value
 * @method PressProductConceptImage setPngLocation()              Sets the current record's "png_location" value
 * @method PressProductConceptImage setPressProductConceptId()    Sets the current record's "press_product_concept_id" value
 * @method PressProductConceptImage setProductId()                Sets the current record's "product_id" value
 * @method PressProductConceptImage setPressProductConcept()      Sets the current record's "PressProductConcept" value
 * @method PressProductConceptImage setProduct()                  Sets the current record's "Product" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePressProductConceptImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('press_product_concept_image');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('jpg_location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('png_location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('press_product_concept_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PressProductConcept', array(
             'local' => 'press_product_concept_id',
             'foreign' => 'id'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}