<?php

/**
 * BasePressLogo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $jpg_location
 * @property string $png_location
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getJpgLocation()  Returns the current record's "jpg_location" value
 * @method string    getPngLocation()  Returns the current record's "png_location" value
 * @method PressLogo setId()           Sets the current record's "id" value
 * @method PressLogo setJpgLocation()  Sets the current record's "jpg_location" value
 * @method PressLogo setPngLocation()  Sets the current record's "png_location" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePressLogo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('press_logo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('jpg_location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('png_location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}