<?php

/**
 * BaseCollections
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $is_active
 * @property Doctrine_Collection $ProductCollection
 * 
 * @method integer             getId()                Returns the current record's "id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getProductCollection() Returns the current record's "ProductCollection" collection
 * @method Collections         setId()                Sets the current record's "id" value
 * @method Collections         setName()              Sets the current record's "name" value
 * @method Collections         setIsActive()          Sets the current record's "is_active" value
 * @method Collections         setProductCollection() Sets the current record's "ProductCollection" collection
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCollections extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collections');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Products as ProductCollection', array(
             'local' => 'id',
             'foreign' => 'collection_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}