<?php

/**
 * BasePressMainArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cover
 * @property string $catalogue
 * @property string $country
 * @property string $description
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method string        getCover()       Returns the current record's "cover" value
 * @method string        getCatalogue()   Returns the current record's "catalogue" value
 * @method string        getCountry()     Returns the current record's "country" value
 * @method string        getDescription() Returns the current record's "description" value
 * @method PressMainArea setId()          Sets the current record's "id" value
 * @method PressMainArea setCover()       Sets the current record's "cover" value
 * @method PressMainArea setCatalogue()   Sets the current record's "catalogue" value
 * @method PressMainArea setCountry()     Sets the current record's "country" value
 * @method PressMainArea setDescription() Sets the current record's "description" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePressMainArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('press_main_area');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cover', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('catalogue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}