<?php

/**
 * BaseIndexNewProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image
 * @property integer $product_id
 * @property Product $Product
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method string          getImage()      Returns the current record's "image" value
 * @method integer         getProductId()  Returns the current record's "product_id" value
 * @method Product         getProduct()    Returns the current record's "Product" value
 * @method IndexNewProduct setId()         Sets the current record's "id" value
 * @method IndexNewProduct setImage()      Sets the current record's "image" value
 * @method IndexNewProduct setProductId()  Sets the current record's "product_id" value
 * @method IndexNewProduct setProduct()    Sets the current record's "Product" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndexNewProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('index_new_product');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}