<?php

/**
 * BaseSliderImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $path
 * @property string $alt
 * 
 * @method integer      getId()   Returns the current record's "id" value
 * @method string       getPath() Returns the current record's "path" value
 * @method string       getAlt()  Returns the current record's "alt" value
 * @method SliderImages setId()   Sets the current record's "id" value
 * @method SliderImages setPath() Sets the current record's "path" value
 * @method SliderImages setAlt()  Sets the current record's "alt" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSliderImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slider_images');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('alt', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}