<?php

/**
 * BaseCatalogueManager
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $path
 * 
 * @method string           getPath() Returns the current record's "path" value
 * @method CatalogueManager setPath() Sets the current record's "path" value
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCatalogueManager extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catalogue_manager');
        $this->hasColumn('path', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}