indexSuccess:
  stylesheets:    [reset.css, style.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface]
  javascripts:    [jquery-1.10.2.js, sidebuttons.js, validator.js, others.js, analytics.js, sidebuttons.js]

all:
  layout: page_layout