showallproductsSuccess:
  stylesheets:    [reset.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface, camera.css, style.css]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js,  validator.js, jquery.min.js, validator.js, analytics.js, jquery.mobile.customized.min.js, jquery.easing.1.3.js, productslider.js,camera.min.js, productslider.js, jquery-1.10.2.js,search-filters.js]
  layout: page_layout

showproductSuccess:
  stylesheets:    [reset.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface, camera.css, style.css]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js,  validator.js, jquery.min.js, validator.js, analytics.js, jquery.mobile.customized.min.js, jquery.easing.1.3.js, productslider.js,camera.min.js, productslider.js, jquery-1.10.2.js]
  layout: page_layout

indexSuccess:
  stylesheets:    [reset.css, bootstrap.min.css, bootstrap-responsive.css, style.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js, validator.js, analytics.js, sidebuttons.js, collection_page.js]

all:
  stylesheets:    [reset.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface,style.css]
  javascripts:    [-*,jquery-1.10.2.js, sidebuttons.js, validator.js, analytics.js, sidebuttons.js]
  layout: page_layout