<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2014/01/10 21:33:19
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineroute' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrinedatabase' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinecli' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sftesterdoctrine' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinegenerator' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfvalidatordoctrineunique' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfwidgetformdoctrinechoice' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinerecord' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinemigratetask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinedatadumptask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuildformstask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildsqltask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuilddbtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedqltask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedataloadtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineinsertsqltask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebuildmodeltask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegenerateadmintask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildschematask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebasetask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinepager' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'swift_doctrinespool' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrineexception' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfformdoctrine' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/var/www/bateye/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',

  // project
  'baseform' => '/var/www/bateye/lib/form/BaseForm.class.php',

  // project_model
  'sliderimages' => '/var/www/bateye/lib/model/doctrine/SliderImages.class.php',
  'categorytable' => '/var/www/bateye/lib/model/doctrine/CategoryTable.class.php',
  'sliderimagestable' => '/var/www/bateye/lib/model/doctrine/SliderImagesTable.class.php',
  'newstable' => '/var/www/bateye/lib/model/doctrine/NewsTable.class.php',
  'category' => '/var/www/bateye/lib/model/doctrine/Category.class.php',
  'contacts' => '/var/www/bateye/lib/model/doctrine/Contacts.class.php',
  'news' => '/var/www/bateye/lib/model/doctrine/News.class.php',
  'products' => '/var/www/bateye/lib/model/doctrine/Products.class.php',
  'contactstable' => '/var/www/bateye/lib/model/doctrine/ContactsTable.class.php',
  'productstable' => '/var/www/bateye/lib/model/doctrine/ProductsTable.class.php',
  'basecategory' => '/var/www/bateye/lib/model/doctrine/base/BaseCategory.class.php',
  'basecollections' => '/var/www/bateye/lib/model/doctrine/base/BaseCollections.class.php',
  'basecontacts' => '/var/www/bateye/lib/model/doctrine/base/BaseContacts.class.php',
  'basenews' => '/var/www/bateye/lib/model/doctrine/base/BaseNews.class.php',
  'baseproductimages' => '/var/www/bateye/lib/model/doctrine/base/BaseProductImages.class.php',
  'basesliderimages' => '/var/www/bateye/lib/model/doctrine/base/BaseSliderImages.class.php',
  'baseproducts' => '/var/www/bateye/lib/model/doctrine/base/BaseProducts.class.php',
  'collections' => '/var/www/bateye/lib/model/doctrine/Collections.class.php',
  'collectionstable' => '/var/www/bateye/lib/model/doctrine/CollectionsTable.class.php',
  'productimages' => '/var/www/bateye/lib/model/doctrine/ProductImages.class.php',
  'productimagestable' => '/var/www/bateye/lib/model/doctrine/ProductImagesTable.class.php',

  // application
  'myuser' => '/var/www/bateye/apps/frontend/lib/myUser.class.php',

  // modules
);
