<?php
// auto-generated by sfViewConfigHandler
// date: 2014/01/20 21:55:21
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('jquery-1.10.2.js', '', array ());
  $response->addStylesheet('bootstrap.js', '', array ());
  $response->addStylesheet('sidebuttons.js', '', array ());
  $response->addStylesheet('parallax.js', '', array ());
  $response->addStylesheet('validator.js', '', array ());
  $response->addStylesheet('others.js', '', array ());


