<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    /**
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getAllCategories(){
        $q = $this->createQuery('Category c');
        return $q->execute();
    }

    public function getAllCategoriesThatHaveProducts()
    {
        $q = $this->createQuery('Category c')
            ->innerJoin('c.ProductCategory pc');

        return $q->execute();
    }

    public function getAllCategoriesThatHaveLoversAtelierProducts()
    {
        $q = $this->createQuery('Category c')
            ->innerJoin('c.LoversAtelierProductCategory lp');

        return $q->execute();
    }
}