<?php

/**
 * CollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Collection');
    }

    /**
     * Returns active collections.
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function showActiveCollections(){
        $q = $this->createQuery('Collection c')
            ->where('c.is_active = 1');
        return $q->execute();
    }
}