<?php

/**
 * Collection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Collection extends BaseCollection
{
    public function postDelete($event)
    {
        $filePath = sfConfig::get('sf_upload_dir') . '/images/collection/' . $this->getNameImage();
        @unlink($filePath);
        $filePath = sfConfig::get('sf_upload_dir') . '/images/collection/' . $this->getBackgroudImage();
        @unlink($filePath);
    }
}
