<?php

/**
 * CollectionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CollectionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CollectionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Collections');
    }
}