<?php

/**
 * IndexNewProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndexNewProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndexNewProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IndexNewProduct');
    }

    /**
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getLatestProduct(){
        $q = $this->createQuery('IndexNewProduct inp')
            ->orderBy('id desc')
            ->limit(1);
        return $q->execute();
    }
}