<?php

/**
 * IndexContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndexContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndexContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IndexContent');
    }

    public function getCatalogueFileName(){
        $q = $this->createQuery('c')
            ->orderBy('c.created_at DESC')
            ->limit(1);
//            Doctrine_Query::create()
//            ->select('catalogue')
//            ->from('IndexContent')
//            ->orderBy('created_at Desc')
//            ->limit(1);
        return $q->execute();
    }

    public static function getTheDesigner(){
        $q = Doctrine_Query::create()
            ->select('*')
            ->from('IndexContent')
            ->orderBy('created_at Desc')
            ->limit(1);
        return $q->execute();
    }
}