<?php

/**
 * IndexContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndexContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndexContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IndexContent');
    }
}