<?php

/**
 * LoversAtelierProductImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoversAtelierProductImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoversAtelierProductImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoversAtelierProductImage');
    }
}