<?php

/**
 * LoversAtelierProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoversAtelierProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoversAtelierProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoversAtelierProduct');
    }

    public function getAllProductsGroupByCategory()
    {
        $q = $this->createQuery("p");

        return $q->execute();
    }
}