<?php

/**
 * LoversTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoversTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoversTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lovers');
    }
}