<?php

/**
 * LoversImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoversImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoversImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LoversImages');
    }
}