<?php

/**
 * PressMainAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressMainAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressMainAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressMainArea');
    }

    /**
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getAllMagazinesWithInfo(){
        $q = $this->createQuery('PressMainArea pma')
        ->orderBy('id desc');
        return $q->execute();
    }
}