<?php

/**
 * PressCollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressCollectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressCollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressCollection');
    }

    /**
     * @param $id
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getProductsByCollection($id){
        $q = Doctrine_Query::create()
            ->from('PressCollection p')
            ->innerJoin('p.Product pr')
            ->where('p.collection_id=' . $id);
        return $q->execute();
    }
}