<?php

/**
 * PressMainAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressMainAreaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressMainAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressMainArea');
    }

    /**
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getAllMagazinesWithInfo()
    {
        $q = $this->createQuery('PressMainArea pma')
        ->orderBy('created_at desc');
        return $q->execute();
    }

    public function getMagazinesYears()
    {
        $q = $this->createQuery('PressMainArea pma')
            ->select('YEAR(created_at)')
            ->orderBy('created_at desc')
            ->groupBy('created_at');
        return $q->execute();
    }
}