<?php

/**
 * PressCatalogueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressCatalogueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressCatalogueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressCatalogue');
    }
}