<?php

/**
 * PressCatalogue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PressCatalogue extends BasePressCatalogue
{
    public function postDelete($event)
    {
        $filepath = sfConfig::get('sf_upload_dir') . '/images/press/catalogue/' . $this->getCover();
        @unlink($filepath);
        $filepath = sfConfig::get('sf_upload_dir') . '/images/press/catalogue/' . $this->getLink();
        @unlink($filepath);
    }
}
