<?php

/**
 * PressProductConceptImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressProductConceptImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressProductConceptImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressProductConceptImage');
    }
}