<?php

/**
 * PressProductConceptTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressProductConceptTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressProductConceptTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressProductConcept');
    }
}