<?php

/**
 * PressLogoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressLogoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressLogoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressLogo');
    }
}