<?php

/**
 * PressCoverImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressCoverImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressCoverImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressCoverImage');
    }
}