<?php

/**
 * PressCoverVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressCoverVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressCoverVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressCoverVideo');
    }
}