<?php

/**
 * PressCollectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PressCollectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PressCollectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PressCollection');
    }
}