<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    public function getAllProducts()
    {
        $q =$this->createQuery("p");
        return $q->execute();
    }

    public function getAllProductsGroupByCategory()
    {
        $q = $this->createQuery("p")
            ->innerJoin('p.Collection')
            ->orderBy('collection_id ASC');
        return $q->execute();
    }

    /**
     * @param $id
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getProductsByCollection($id){
        $q = Doctrine_Query::create()
            ->from('Product p')
            ->where('p.collection_id=' . $id);
        return $q->execute();
    }
}