<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bateye
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    /**
     * @param $id
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getById($id){
        $q = Doctrine_Query::create()
            ->from('Product p')
            ->where("id=?", $id);

        return $q->execute();
    }

    public function postDelete($event)
    {
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getMainImgPath();
        @unlink($filePath);
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getSmallImg();
        @unlink($filePath);
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getContextImg();
        @unlink($filePath);
        parent::postDelete($event);
    }

    public function preUpdate($event)
    {
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getMainImgPath();
        @unlink($filePath);
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getSmallImg();
        @unlink($filePath);
        $filePath = sfConfig::get('sf_upload_dir') . '/images/products/' . $this->getContextImg();
        @unlink($filePath);
        parent::postDelete($event);
    }
}
