<?php

/**
 * SliderImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SliderImages');
    }

    public function getAllSliders(){
//        $q = $this->createQuery()
//            ->select('*')
//            ->from('SliderImages')
//            ->orderBy('created_at DESC');
        $q = $this->createQuery('a')
            ->orderBy('a.created_at DESC');
        return $q->execute();
    }
}