<?php

/**
 * SliderImagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderImagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderImagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SliderImages');
    }
}