# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
# http://www.symfony-project.org/reference/1_4/en/10-Routing

press_show_product:
  url:  /press/showproduct/:id
  param: { module: press, action: showproduct }
  requirements:
    id: \d+
    sf_method: [get]

press_cover_videos_success:
  url:  /press/videos/
  param: { module: press, action: covervideos }

press_press_releases_success:
  url:  /press/press_releases/
  param: { module: press, action: pressreleases }

press_cover_images_success:
  url:  /press/covers_images/
  param: { module: press, action: coverimages }

press_catalogue_success:
  url:  /press/catalogues/
  param: { module: press, action: catalogues }

press_show_collection:
  url:      /press/showcollection/:id/:name
  class:    sfDoctrineRoute
  options:  { model: Product, type: object }
  param:    { module: press, action: showcollection }
  requirements:
    id: \d+
    sf_method: [get]

press_thebrand:
  url:  /press/thebrand/
  param: { module: press, action: thebrand }

press:
  url:  /press/
  param: { module: press, action: index }

#the brand module
thebrand:
  url:  /thebrand/
  param: { module: thebrand, action: index }

show_concept:
  url:  /thebrand/concept/
  param: { module: thebrand, action: showconcept }

show_history:
  url:  /thebrand/history/
  param: { module: thebrand, action: showhistory}

show_manufacture:
  url:  /thebrand/manufacture/
  param: { module: thebrand, action: showmanufacture}

show_author:
  url:  /thebrand/author/
  param: { module: thebrand, action: showauthor}

#contacts module
contacts:
  url: /contacts/
  param: { module: contacts, action: index }

send_mail:
  url:  /contacts/sendmail
  param: { module: contacts, action: sendmail }
  requirements:
    sf_method: [post]

#Collections & products
collection:
  url:   /collection/
  param: { module: collection, action: index }

show_collection:
  url:      /collection/showcollection/:id/:name
  class:    sfDoctrineRoute
  options:  { model: Category, type: object }
  param:    { module: collection, action: showcollection }
  requirements:
    id: \d+
    sf_method: [get]

show_product:
  url:  /collection/showproduct/:id/:name
  param: { module: collection, action: showproduct }
  requirements:
    id: \d+
    sf_method: [get]

show_allproducts:
  url:   /showallproducts/*
  param: { module: collection, action: showallproducts }

show_allatelierproducts:
  url:   /lovers-atelier/products/*
  param: { module: collection, action: showallatelierproducts }

show_loversatelierproduct:
  url:  /lovers-atelier/showproduct/:id/:name
  param: { module: collection, action: showloversatelierproduct }
  requirements:
    id: \d+
    sf_method: [get]

#Deprecated
#Lovers & its products
#lovers:
#  url:   /lovers/
#  param: { module: lovers, action: index }
#
#show_loversproduct:
#  url:  /lovers/showloversproduct/:id/:name
#  param: { module: lovers, action: showloversproduct }
#  requirements:
#    id: \d+
#    sf_method: [get]

#Media files and others
mediafile:
  url: /media/
  param: { module: media, action: show }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*