# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

#the brand module
thebrand:
  url:  /thebrand/
  param: { module: thebrand, action: index}

show_concept:
  url:  /thebrand/concept/
  param: { module: thebrand, action: showconcept}

show_history:
  url:  /thebrand/history/
  param: { module: thebrand, action: showhistory}

show_manufacture:
  url:  /thebrand/manufacture/
  param: { module: thebrand, action: showmanufacture}

show_author:
  url:  /thebrand/author/
  param: { module: thebrand, action: showauthor}

#contacts module
contacts:
  url: /contacts/
  param: { module: contacts, action: index }

send_mail:
  url:  /contacts/sendmail
  param: { module: contacts, action: sendmail }
  requirements:
    sf_method: [post]

#Collections & products
collection:
  url:   /collection/
  param: { module: collection, action: index }

show_collection:
  url:   /collection/showcollection/:id/:name
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param: { module: collection, action: showcollection }
  requirements:
    id: \d+
    sf_method: [get]

show_product:
  url:  /collection/showproduct/:id/:name
  param: { module: collection, action: showproduct }
  requirements:
    id: \d+
    sf_method: [get]

#Lovers & its products
lovers:
  url:   /lovers/
  param: { module: lovers, action: index }

show_loverscollection:
  url:   /lovers/showloverscollection/:id/:name
  class:   sfDoctrineRoute
  options: { model: Category, type: object }
  param: { module: collection, action: showloverscollection }
  requirements:
    id: \d+
    sf_method: [get]

show_loversproduct:
  url:  /lovers/showloversproduct/:id/:name
  param: { module: collection, action: showloversproduct }
  requirements:
    id: \d+
    sf_method: [get]

#Media files and others
mediafile:
  url: /media/:catalogue.pdf/*
  param: { module: media, action: show }