<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/02/23 17:08:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bateye',
  'username' => 'root',
  'password' => 'C@r0L87',
  'name' => 'doctrine',
)),);
