<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/06/26 21:16:40
sfConfig::add(array(
  'mod_product_images_enabled' => true,
  'mod_product_images_view_class' => 'sfPHP',
));
