<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/02/24 14:32:01
$this->security = array (
  'sf_guard_user' => 
  array (
    'credentials' => 'super_user',
  ),
  'autosfguardgroup' => 
  array (
    'credentials' => 'super_user',
  ),
  'sf_guard_permission' => 
  array (
    'credentials' => 'super_user',
  ),
  'sf_guard_register' => 
  array (
    'credentials' => 'super_user',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_user',
        1 => 'admin',
      ),
    ),
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
);
