<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/24 22:55:31
$this->security = array (
  'sf_guard_user' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_user',
      ),
    ),
  ),
  'autosfguardgroup' => 
  array (
    'credentials' => 'super_user',
  ),
  'sf_guard_permission' => 
  array (
    'credentials' => 'super_user',
  ),
  'sf_guard_register' => 
  array (
    'credentials' => 'super_user',
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_user',
        1 => 'admin',
      ),
    ),
  ),
);
