<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/31 19:56:27
sfConfig::add(array(
  'mod_product_images_enabled' => true,
  'mod_product_images_view_class' => 'sfPHP',
));
