all:
  stylesheets:    [normalize.min.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface,style.css]
  javascripts:    [-*,jquery-1.10.2.min.js, sidebuttons.min.js, validator.min.js, analytics.min.js, sidebuttons.min.js]