generator:
  class: sfDoctrineGenerator
  param:
    model_class:           IndexContent
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          index_content
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: { _edit: ~ }
      fields:  ~
      list:
        actions: {}
        batch_actions: {}
        object_actions: { _edit: ~ }
      filter:
        class: false
      form:    ~
      edit:
        actions: { _list: ~, _save: ~ }
      new:     ~
