secureSuccess:
  stylesheets:    [normalize.min.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface, camera.css, bootstrap3.min.css, style.css]
  javascripts:    [-*,jquery-1.10.2.min.js, sidebuttons.min.js,  validator.min.js, jquery.min.js, validator.min.js, analytics.min.js, jquery.mobile.customized.min.js, jquery.easing.1.3.min.js, productslider.min.js,camera.min.js, productslider.min.js,jquery-1.10.2.min.js]
  layout: page_layout

signinSuccess:
  stylesheets:    [normalize.min.css, main.css, "http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900", http://fonts.googleapis.com/css?family=Abril+Fatface, camera.css, bootstrap3.min.css, style.css]
  javascripts:    [-*,jquery-1.10.2.min.js, sidebuttons.min.js,  validator.min.js, jquery.min.js, validator.min.js, analytics.min.js, jquery.mobile.customized.min.js, jquery.easing.1.3.min.js, productslider.min.js,camera.min.js, productslider.min.js,jquery-1.10.2.min.js]
  layout: page_layout