<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/29 22:32:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bateye_main',
  'username' => 'bateye_main',
  'password' => 'Pedro13249976',
  'name' => 'doctrine',
)),);
