<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('lovers', 'lovers_collection_id_collections_id', array(
             'name' => 'lovers_collection_id_collections_id',
             'local' => 'collection_id',
             'foreign' => 'id',
             'foreignTable' => 'collections',
             ));
        $this->createForeignKey('lovers', 'lovers_category_id_category_id', array(
             'name' => 'lovers_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('lovers_images', 'lovers_images_product_id_products_id', array(
             'name' => 'lovers_images_product_id_products_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'products',
             ));
        $this->addIndex('lovers', 'lovers_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
        $this->addIndex('lovers', 'lovers_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('lovers_images', 'lovers_images_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('lovers', 'lovers_collection_id_collections_id');
        $this->dropForeignKey('lovers', 'lovers_category_id_category_id');
        $this->dropForeignKey('lovers_images', 'lovers_images_product_id_products_id');
        $this->removeIndex('lovers', 'lovers_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
        $this->removeIndex('lovers', 'lovers_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('lovers_images', 'lovers_images_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}