<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('lovers_images', 'lovers_images_product_id_products_id');
        $this->createForeignKey('lovers_images', 'lovers_images_product_id_lovers_id', array(
             'name' => 'lovers_images_product_id_lovers_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'lovers',
             ));
        $this->addIndex('lovers_images', 'lovers_images_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('lovers_images', 'lovers_images_product_id_products_id', array(
             'name' => 'lovers_images_product_id_products_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'products',
             ));
        $this->dropForeignKey('lovers_images', 'lovers_images_product_id_lovers_id');
        $this->removeIndex('lovers_images', 'lovers_images_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}