<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('press_product_image', 'press_product_image_collection_id_press_collection_id');
        $this->createForeignKey('press_collection', 'press_collection_product_id_product_id', array(
             'name' => 'press_collection_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->createForeignKey('press_product_image', 'press_product_image_collection_id_collection_id', array(
             'name' => 'press_product_image_collection_id_collection_id',
             'local' => 'collection_id',
             'foreign' => 'id',
             'foreignTable' => 'collection',
             ));
        $this->addIndex('press_collection', 'press_collection_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('press_product_image', 'press_product_image_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('press_product_image', 'press_product_image_collection_id_press_collection_id', array(
             'name' => 'press_product_image_collection_id_press_collection_id',
             'local' => 'collection_id',
             'foreign' => 'id',
             'foreignTable' => 'press_collection',
             ));
        $this->dropForeignKey('press_collection', 'press_collection_product_id_product_id');
        $this->dropForeignKey('press_product_image', 'press_product_image_collection_id_collection_id');
        $this->removeIndex('press_collection', 'press_collection_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('press_product_image', 'press_product_image_collection_id', array(
             'fields' => 
             array(
              0 => 'collection_id',
             ),
             ));
    }
}