<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('index_new_product', 'index_new_product_product_id_product_id', array(
             'name' => 'index_new_product_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             ));
        $this->addIndex('index_new_product', 'index_new_product_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('index_new_product', 'index_new_product_product_id_product_id');
        $this->removeIndex('index_new_product', 'index_new_product_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}