<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'home_text', 'string', '255', array());
    }

    public function down()
    {
        $this->removeColumn('product', 'home_text');
    }
}