<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('lovers_atelier_product', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'main_img_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'main_img_alt' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'context_img' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'context_img_alt' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'small_img' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'small_img_alt' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'citation' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '1200',
             ),
             'designer' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'dimensions' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'materials' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'other' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'home_featured' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '0',
              'length' => '25',
             ),
             'home_text' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('lovers_atelier_product_image', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'location' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'alt' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('lovers_atelier_product');
        $this->dropTable('lovers_atelier_product_image');
    }
}