<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/06/13 02:22:34
sfConfig::add(array(
  'app_bootstrap_admin_labelcols' => 4,
  'app_bootstrap_admin_fieldcols' => 8,
  'app_sf_guard_plugin_success_signin_url' => '@press_thebrand',
  'app_sf_guard_plugin_success_signout_url' => 'press/index',
));
