<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/01/13 01:14:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bateye',
  'username' => 'root',
  'password' => 'C@r0L87',
  'name' => 'doctrine',
)),);
