<?php
// auto-generated by sfViewConfigHandler
// date: 2014/01/13 21:23:02
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Bat Eye', false, false);
  $response->addMeta('description', 'Bat Eye is a design brand with exclusive furniture to decorate interiors with the most exquisite, artistic design. It wants to bring the impressive interior design with it&#039;s exclusive luxury furniture, delivered by Marco Sousa who is inspired by cities like Porto.', false, false);
  $response->addMeta('keywords', 'design furniture, luxury furniture manufacturers, customized furniture, furniture store, living room furniture, signature furniture, interior design, exquisite furniture, Marco Sousa, artisan, handmade, luxury pieces', false, false);
  $response->addMeta('language', 'pt', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-responsive.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('style.css', '', array ());
  $response->addJavascript('jquery-1.10.2.js', '', array ());
  $response->addJavascript('bootstrap.js', '', array ());
  $response->addJavascript('sidebuttons.js', '', array ());
  $response->addJavascript('parallax.js', '', array ());
  $response->addJavascript('validator.js', '', array ());
  $response->addJavascript('others.js', '', array ());


