<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/09/27 13:30:42
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'user',
    ),
  ),
);
