<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/06/26 23:48:15
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super_user',
        1 => 'admin',
        2 => 'user',
      ),
    ),
  ),
);
