indexSuccess:
  stylesheets:    [normalize.min.css, bootstrap.min.css, swiper.min.css, style.css]
  javascripts:    [jquery-1.10.2.min.js, sidebuttons.min.js, parallax.min.js, validator.min.js, swiper.jquery.min.js, others.min.js, bootstrap.min.js]
  metas:
    viewport:     width=device-width, initial-scale=1.0