indexSuccess:
  stylesheets:    [reset.css, bootstrap.min.css, bootstrap-responsive.css, style.css]
  javascripts:    [jquery-1.10.2.js, bootstrap.js, sidebuttons.js, parallax.js, validator.js, others.js]

showSuccess:
  has_layout: false
  http_metas:
    content-type: application/pdf