# config/doctrine/schema.yml
Products:
  actAs:            { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    name:           { type: string(255), notnull: true }
    main_img_path:  { type: string(255), notnull: true }
    citation:       { type: string(255), notnull: true }
    description:    { type: string(255), notnull: true }
    designer:       { type: string(255) }
    width:          { type: string(255) }
    height:         { type: string(255) }
    diameter:       { type: string(255) }
    depth:          { type: string(255) }
    other:          { type: string(255) }
    collection_id:  { type: integer, notnull: true }
    category_id:    { type: integer, notnull: true }
  relations:
    Collections:    { local: collection_id, foreign: id, foreignAlias: ProductCollection }
    Category:     { local: category_id, foreign: id, foreignAlias: ProductCategory }

ProductImages:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    product_id:     { type: integer, notnull: true }
    location:       { type: string(255), notnull:true }
  relations:
    Products:       { local: product_id, foreign: id, foreignAlias: ProductImage }

Collections:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    name:           { type: string(255), notnull: true }
    is_active:      { type: boolean, notnull: true, default: 1 }

Category:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    name:           { type: string(255), notnull: true }

SliderImages:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    path:           { type: string(255), notnull: true }

News:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    news_title:     { type: string(255), notnull: true }
    news_content:   { type: string(255), notnull: true }
    news_image:     { type: string(255), notnull: true }

Contacts:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    email:          { type: string(150), notnull: true }
    phone:          { type: string(150), notnull: true }