# config/doctrine/schema.yml
Product:
  actAs:              { Timestampable: ~ }
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    name:             { type: string(255), notnull: true }
    main_img_path:    { type: string(255), notnull: true }
    main_img_alt:     { type: string(255), notnull: true }
    context_img:      { type: string(255), notnull: true }
    context_img_alt:  { type: string(255), notnull: true }
    small_img:        { type: string(255) }
    small_img_alt:    { type: string(255) }
    citation:         { type: string(255), notnull: true }
    description:      { type: string(1200), notnull: true }
    designer:         { type: string(255) }
    dimensions:       { type: string(255) }
    materials:        { type: string(255) }
    other:            { type: string(255) }
    collection_id:    { type: integer, notnull: true }
    category_id:      { type: integer, notnull: true }
  relations:
    Collection:       { local: collection_id, foreign: id, foreignAlias: ProductCollection }
    Category:         { local: category_id, foreign: id, foreignAlias: ProductCategory }

ProductImage:
  actAs:            { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    product_id:     { type: integer, notnull: true }
    location:       { type: string(255), notnull: true }
    alt:            { type: string(255), notnull: true }
  relations:
    Product:        { local: product_id, foreign: id, foreignAlias: ProductImage }

Collection:
  actAs:              { Timestampable: ~ }
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    name:             { type: string(255), notnull: true }
    name_image:       { type: string(255), notnull: true }
    backgroud_image:  { type: string(255), notnull: true }
    is_active:        { type: boolean, notnull: true, default: 1 }

Category:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    name:           { type: string(255), notnull: true }
    image:          { type: string(255), notnull: true }
    alt:            { type: string(255), notnull: true }

SliderImage:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    path:           { type: string(255), notnull: true }
    alt:            { type: string(255), notnull: true }

News:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    news_title:     { type: string(255), notnull: true }
    news_content:   { type: string(1000), notnull: true }
    news_image:     { type: string(255), notnull: true }
    link:           { type: string(255), notnull: true }

Contacts:
  actAs: { Timestampable: ~ }
  columns:
    email:          { type: string(255), notnull: true }
    phone:          { type: string(255), notnull: true }

IndexContent:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    newsletter:     { type: string(500), notnull: true }
    catalogue:      { type: string(500), notnull: true }
    thebrand:       { type: array, notnull: true }
    thedesigner:    { type: array, notnull: true }

#Main area before login
PressMainArea:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    cover:          { type: string(255), notnull: true }
    catalogue:      { type: string(255), notnull: true }

###################################
####### Press main area ###########
###################################
PressLogo:
  actAs: { Timestampable: ~ }
  columns:
    id:             { type: integer, primary: true, autoincrement: true }
    jpg_location:   { type: string(255), notnull: true }
    png_location:   { type: string(255), notnull: true }

#The brand press page Concept mini gallery + product gallery for single images
PressProductConcept:
  actAs: { Timestampable: ~ }
  columns:
    id:                { type: integer, primary: true, autoincrement: true }
    package_location:  { type: string(255), notnull: true }
    image:             { type: string(255), notnull: true }
    product_id:        { type: integer, notnull: true }
  relations:
    Product:           { local: product_id, foreign: id, foreignAlias: PressConceptProduct }

#Individual gallery for each product concept
PressProductConceptImage:
  actAs: { Timestampable: ~ }
  columns:
    id:                       { type: integer, primary: true, autoincrement: true }
    image:                    { type: string(255), notnull: true }
    jpg_location:             { type: string(255), notnull: true }
    png_location:             { type: string(255), notnull: true }
    press_product_concept_id: { type: integer, notnull: true }
    product_id:               { type: integer, notnull: true }
  relations:
    PressProductConcept:      { local: press_product_concept_id, foreign: id, foreignAlias: PressProductConcept }
    Product:                  { local: product_id, foreign: id, foreignAlias: PressProductImage }

##########################################
######## Press collections area ##########
###### Here is the collection page #######
##########################################
PressCollection:
  actAs: { Timestampable: ~ }
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    product_image:    { type: string(255), notnull: true }
    package_location: { type: string(255), notnull: true }
    collection_id:    { type: integer, notnull: true }
  relations:
    Collection:       { local: collection_id, foreign: id, foreignAlias: PressCollection }

##########################################
####### Product individual gallery #######
##########################################
PressProductImage:
  actAs: { Timestampable: ~ }
  columns:
    id:                { type: integer, primary: true, autoincrement: true }
    high_res_img:      { type: string(255), notnull: true }
    low_res_img:       { type: string(255), notnull: true }
    collection_id:     { type: integer, notnull: true }
    product_id:        { type: integer, notnull: true }
  relations:
    PressCollection:   { local: collection_id, foreign: id, foreignAlias: PressCollection }
    Product:           { local: product_id, foreign: id, foreignAlias: PressProductImage }

##########################################
############# Other areas ################
##########################################
PressCatalogue:
  actAs: { Timestampable: ~ }
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    link:         { type: string(255), notnull: true }
    cover:        { type: string(255), notnull: true }

PressRelease:
  actAs: { Timestampable: ~ }
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    link:         { type: string(255), notnull: true }
    cover:        { type: string(255), notnull: true }

PressCoverImage:
  actAs: { Timestampable: ~ }
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    link:         { type: string(255), notnull: true }
    cover:        { type: string(255), notnull: true }

PressCoverVideo:
  actAs: { Timestampable: ~ }
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    link:         { type: string(255), notnull: true }